name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.8'
      
    - uses: actions/setup-python@v1
      name: Install Python 3.7
      with:
        python-version: '3.7'

    - uses: actions/setup-python@v1
      name: Install Python 3.6
      with:
        python-version: '3.6'

    - uses: actions/setup-python@v1
      name: Install Python 3.5
      with:
        python-version: '3.5'

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.3.0

    - name: Install Visual C++ for Python 2.7
      if: startsWith(matrix.os, 'windows')
      run: |
        choco install vcpython27 -f -y

    - name: Set up VS Envs for Windows
      if: startsWith(matrix.os, 'windows')
      # https://github.com/actions/virtual-environments/issues/294#issuecomment-588090582
      run: |
        function Invoke-VSDevEnvironment {
          $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          $installationPath = & $vswhere -prerelease -legacy -latest -property installationPath
          $Command = Join-Path $installationPath "Common7\Tools\vsdevcmd.bat"
          & "${env:COMSPEC}" /s /c "`"$Command`" -no_logo && set" | Foreach-Object {
              if ($_ -match '^([^=]+)=(.*)') {
                  [System.Environment]::SetEnvironmentVariable($matches[1], $matches[2])
              }
          }
        }
        Invoke-VSDevEnvironment

    - name: Checkout submodules
      shell: bash
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive --depth=1

    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt

    - name: Tests
      run: |
        tox

    - name: Build wheel
      if: contains(github.ref, 'tags/')
      run: |
        python -m cibuildwheel --output-dir wheelhouse

    - uses: actions/upload-artifact@v1
      if: contains(github.ref, 'tags/')
      with:
        name: wheels
        path: ./wheelhouse
