name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: windows-latest
    strategy:
      matrix:
        config:
          - name: MSVC x86
            arch: x86

          - name: MSVC x64
            arch: amd64

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.8'
      
    - uses: actions/setup-python@v1
      name: Install Python 3.7
      with:
        python-version: '3.7'

    - uses: actions/setup-python@v1
      name: Install Python 3.6
      with:
        python-version: '3.6'

    - uses: actions/setup-python@v1
      name: Install Python 3.5
      with:
        python-version: '3.5'

    - name: Install Visual C++ for Python 2.7
      run: |
        choco install vcpython27 -f -y

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.3.0

    - name: Set up VS Envs for Windows
      run: |
        function Invoke-VSDevEnvironment {
          $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          $installationPath = & $vswhere -prerelease -legacy -latest -property installationPath
          $Command = Join-Path $installationPath "Common7\Tools\vsdevcmd.bat"
          & "${env:COMSPEC}" /s /c "`"$Command`" -no_logo && set" | Foreach-Object {
              if ($_ -match '^([^=]+)=(.*)') {
                  [System.Environment]::SetEnvironmentVariable($matches[1], $matches[2])
              }
          }
        }
        Get-Command rc.exe | Format-Table -AutoSize
        Invoke-VSDevEnvironment

    - name: Checkout submodules
      shell: bash
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive --depth=1

    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt

    - name: Test for Python 3.8
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -no_logo -arch=${{ matrix.config.arch }}
        tox -e py38

    - name: Test for Python 3.7
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -no_logo -arch=${{ matrix.config.arch }}
        tox -e py37

    - name: Test for Python 3.6
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -no_logo -arch=${{ matrix.config.arch }}
        tox -e py36

    - name: Test for Python 3.5
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -no_logo -arch=${{ matrix.config.arch }}
        tox -e py35

    - name: Test for Python 2.7
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -no_logo -arch=${{ matrix.config.arch }}
        tox -e py27

    - name: Build wheel
      if: contains(github.ref, 'tags/')
      run: |
        python -m cibuildwheel --output-dir wheelhouse

    - uses: actions/upload-artifact@v1
      if: contains(github.ref, 'tags/')
      with:
        name: wheels
        path: ./wheelhouse
