name: Test (dev)

on:
  push:
    branches: [dev]
    paths-ignore:
      - '**.md'
      - '**.rst'
  pull_request:
    branches: [dev]
    paths-ignore:
      - '**.md'
      - '**.rst'

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yml
